### ISSUE TITLE
Переведите мне все эти слова

### ISSUE THREAD

**Issue by kuritsynsergeysergeevich** [kirush0280/scenes_okbit#53]
вообще не понятно что значит название этой вкладки но роде как что то можно писать, посмотрим что из этого выйдет
![режим эко](https://user-images.githubusercontent.com/60663686/78997325-07b29b80-7b4f-11ea-9f84-4630ca305590.png)

**Comment by Zaitsev-ap** [comment]
И коментировать

**Comment by kuritsynsergeysergeevich** [comment]
> вообще не понятно что значит название этой вкладки но роде как что то можно писать, посмотрим что из этого выйдет
> ![режим эко](https://user-images.githubusercontent.com/60663686/78997325-07b29b80-7b4f-11ea-9f84-4630ca305590.png)
